version: "3"

services:
    app:
        stdin_open: true
        build: .
        image: appusers
        container_name: appusers
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - "./landingpage:/opt/app"
            - "/opt/app/node_modules"
            - "/opt/app/.next"
        environment:
            - CHOKIDAR_USEPOLLING=true
        #command: yarn dev            
